version: "3.7"
services:
  backend:
    container_name: app_dev
    image: app:build
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
        - CONTEXT=app
    networks:
      - dev_net
    ports:
      - 8081:8080
    environment:
      - DATABASE_HOST=falenciapessoal
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWD=baal

networks:
  dev_net: