version: "3.7"
services:
  db:
    container_name: dbFalencia
    image: postgres:9.6
    ports:
      - 5432:5432
    networks:
      - dev_net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=falenciapessoal
    restart: "always"

networks:
  dev_net:
