version: "3.7"
services:
  backend:
    container_name: app-dev
    image: app:build${BUILD_NUMBER}
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
        - CONTEXT=app
    networks:
      - dev_net
    ports:
      - 85:9090
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWD=postgres

networks:
  dev_net: