version: "3.7"
services:
  backend:
    containername: app-dev
    image: app:build
    build:
      context: .
      args:
        - WAR_FILE=target/*.war
        - CONTEXT=app
    #   networks:
    #     - dev_net
    ports:
      - 8081:8080
  #  environment:
  #   - DATABASE_HOST=db
  #  - DATABASE_PORT=5432
  # - DATABASE_USER=postgres
  #- DATABASE_PASSWD=postgres

  #networks:
  #dev_net: