version: "3.7"
services:
  db:
    container_name: dbFalencia
    image: postgres:9.6
    ports:
      - 5432:5432
    networks:
      - dev_net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=falenciapessoal
    restart: "always"
    #volumes:
    #  - dev_postgresql:/var/lib/postgresql
    #  - dev_postgresql_data:/var/lib/postgresql/data

networks:
  dev_net:

#volumes:
#  dev_postgresql:
#  dev_postgresql_data: