pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Estou na Build'
            }
        }
        stage('Test') {
            steps {
                 echo 'Estou na Test'
            }
        }
        stage('Deploy') {
             steps {
                   echo 'Estou na Deploy'
             }
        }
    }
}